

services:
  postgres:
    image: postgres:15-alpine
    container_name: strapi_postgres
    restart: unless-stopped
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - strapi-net

  strapi:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: strapi_app
    restart: unless-stopped
    env_file:
      - .env
    environment:
      NODE_ENV: development
    depends_on:
      - postgres
    ports:
      - "1337:1337"
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    networks:
      - strapi-net

  nginx:
    image: nginx:stable-alpine
    container_name: strapi_nginx
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - strapi
    networks:
      - strapi-net

volumes:
  postgres_data:

networks:
  strapi-net:
    name: strapi-net
